input_dir: outputs/fiper_rollout_recording/2025-12-09/16-31-11_flow_matching_pusht

dataset:
  repo_id: lerobot/pusht

env:
  type: pusht

fiper_rollout_scorer:
  scores_by_method:
    bayesian_laplace: [mode_distance, inter_vel_diff, likelihood]
    bayesian_ensemble: [mode_distance, inter_vel_diff, likelihood]
    composed: [mode_distance, inter_vel_diff, likelihood]
    composed_bayesian_laplace: [mode_distance, inter_vel_diff, likelihood]
    composed_bayesian_ensemble: [mode_distance, inter_vel_diff, likelihood]
  
  terminal_vel_eval_times: [0, 0.05, 0.1, 0.15, 0.2, 0.25]
  ensemble_model_paths: [
    outputs/train/flow_matching/pusht_02/checkpoints/200000/pretrained_model,
    outputs/train/flow_matching/pusht_03/checkpoints/200000/pretrained_model,
    outputs/train/flow_matching/pusht_04/checkpoints/200000/pretrained_model,
  ]
  laplace_config:
    scopes: [velocity_last, rgb_last]
    calib_fraction: 1.0
    num_samples: 3

# start_episode: 0
# end_episode: 19

# python src/lerobot/scripts/fiper_data_generation/score_fiper_rollout.py --config=configs/flow_matching/score_fiper_rollout/pusht.yaml --policy.path=outputs/train/flow_matching/pusht_01/checkpoints/200000/pretrained_model
