env:
  type: libero
  task: libero_10
  task_ids: [0, 4, 7, 8, 9]

fiper_rollout_recorder:
  num_uncertainty_sequences: 64
  ode_eval_times: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]

n_calib_episodes: 50
n_test_episodes: 150

seed: 28
job_name: flow_matching_libero

# python src/lerobot/scripts/fiper_data_generation/record_fiper_rollout.py --config=configs/flow_matching/record_fiper_rollout/libero.yaml --policy.path=outputs/train/flow_matching/libero_01/checkpoints/050000/pretrained_model