dataset:
  repo_id: lerobot/pusht

env:
  type: pusht

policy:
  type: flow_matching
  device: cuda
  repo_id: bensturgis/flow-matching-pusht-01

output_dir: outputs/train/flow_matching/test
batch_size: 64
steps: 200000
eval_freq: 20000
save_freq: 20000
seed: 42
wandb:
  enable: true