dataset:
  repo_id: JohannesSaut/insert_lego_merged

policy:
  type: smolvla
  device: cuda
  repo_id: bensturgis/smolvla-lego-stacking-finetuning-01

output_dir: outputs/train/smolvla/lego_stacking_finetuning_01
steps: 200000
batch_size: 48
save_freq: 10000
enable_val_loss: False
seed: 187
wandb:
  enable: true
job_name: lego_stacking_finetuning_01

# python src/lerobot/scripts/train.py --config=configs/smolvla/train/lego_stacking_finetuning.yaml --policy.path=outputs/train/smolvla/libero_base/checkpoints/030000/pretrained_model --policy.repo_id=bensturgis/lego_stacking_finetuning_01