input_dir: outputs/fiper_rollout_recording/smolvla/libero_10

dataset:
  repo_id: HuggingFaceVLA/libero
  libero_tasks: {
    libero_spatial: [],
    libero_object: [],
    libero_goal: [],
    libero_10: [0, 4, 7, 8, 9]
  }

env:
  type: libero
  task: libero_10
  task_ids: [0, 4, 7, 8, 9]

fiper_rollout_scorer:
  scores_by_method:
    bayesian_laplace: [mode_distance, inter_vel_diff]
    bayesian_ensemble: [mode_distance, inter_vel_diff]
    composed: []
    composed_bayesian_laplace: []
    composed_bayesian_ensemble: []
  
  terminal_vel_eval_times: [0]
  ensemble_model_paths: [
    outputs/train/smolvla/libero_finetuned_02/checkpoints/015000/pretrained_model,
    outputs/train/smolvla/libero_finetuned_03/checkpoints/015000/pretrained_model,
    outputs/train/smolvla/libero_finetuned_04/checkpoints/015000/pretrained_model,
    outputs/train/smolvla/libero_finetuned_05/checkpoints/015000/pretrained_model,
    outputs/train/smolvla/libero_finetuned_06/checkpoints/015000/pretrained_model,
  ]
  laplace_config:
    scopes: [action_out_proj]
    calib_fraction: 1.0
    num_samples: 5

output_dir: outputs/fiper_rollout_scoring/smolvla/libero_10_5_scorers

seed: 15

# python src/lerobot/scripts/fiper_data_generation/score_fiper_rollout.py --config=configs/smolvla/score_fiper_rollout/libero.yaml --policy.path=outputs/train/smolvla/libero_finetuned_01/checkpoints/015000/pretrained_model