input_dir:

dataset:
  repo_id: HuggingFaceVLA/libero
  libero_tasks: {
    libero_spatial: [],
    libero_object: [],
    libero_goal: [],
    libero_10: [0, 4, 7, 8, 9]
  }

fiper_rollout_scorer:
  terminal_vel_eval_times: [0, 0.05, 0.1, 0.15, 0.2, 0.25]
  ensemble_model_paths: [
    outputs/train/smolvla/libero_finetuned_02/checkpoints/010000/pretrained_model,
    outputs/train/smolvla/libero_finetuned_03/checkpoints/010000/pretrained_model,
    outputs/train/smolvla/libero_finetuned_04/checkpoints/010000/pretrained_model,
  ]
  laplace_config:
    scopes: [action_out_proj]
    calib_fraction: 1.0
    num_samples: 3

# python src/lerobot/scripts/fiper_data_generation/record_fiper_rollout.py --config=configs/smolvla/record_fiper_rollout/libero.yaml --policy.path=outputs/train/smolvla/libero_finetuned_01/checkpoints/010000/pretrained_model